### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by im-yuria** [ashin-15/StarVim#27]
**Describe the bug**
The link for discord on README is broken

**To Reproduce**
1. Go to 'README.md'
2. Click on 'discord link' without account in the server
3. See error

**Expected behavior**
A invite to server

**Additional context**

**Comment by ashincoder** [comment]
https://github.com/ashincoder/StarVim/commit/24d1f2077885415b2c4dd816d997834af1b3b884
How about now.
